### ISSUE TITLE
unable to start the application

### ISSUE THREAD

**Issue by akhlaaqbadulla** [harishanchu/workplace-backend#1]
Hello,
i have been trying to set up the application for testing. but i cannot seem to be abl to even start the application. all y configuration are correct but it still wont start. am etting this error.

> > Workplace@1.0.0 start-production /home/admin/workplace
> > NODE_ENV=development node .
> 
> Connection fails: Error: getaddrinfo ENOTFOUND mysql mysql:3306
> It will be retried for the next request.
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: getaddrinfo ENOTFOUND mysql mysql:3306
>     at errnoException (dns.js:50:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
>     --------------------
>     at Protocol._enqueue (/home/admin/workplace/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>     at Protocol.handshake (/home/admin/workplace/node_modules/mysql/lib/protocol/Protocol.js:51:23)
>     at PoolConnection.connect (/home/admin/workplace/node_modules/mysql/lib/Connection.js:118:18)
>     at Pool.getConnection (/home/admin/workplace/node_modules/mysql/lib/Pool.js:48:16)
>     at MySQL.connect (/home/admin/workplace/node_modules/loopback-connector-mysql/lib/mysql.js:90:17)
>     at Object.initializeDataSource [as initialize] (/home/admin/workplace/node_modules/loopback-connector-mysql/lib/mysql.js:44:28)
>     at DataSource.setup (/home/admin/workplace/node_modules/loopback-datasource-juggler/lib/datasource.js:493:19)
>     at new DataSource (/home/admin/workplace/node_modules/loopback-datasource-juggler/lib/datasource.js:138:8)
>     at Registry.createDataSource (/home/admin/workplace/node_modules/loopback/lib/registry.js:364:12)
>     at dataSourcesFromConfig (/home/admin/workplace/node_modules/loopback/lib/application.js:570:19)
>     at Function.app.dataSource (/home/admin/workplace/node_modules/loopback/lib/application.js:269:14)
>     at /home/admin/workplace/node_modules/loopback-boot/lib/executor.js:191:9
>     at /home/admin/workplace/node_modules/loopback-boot/lib/executor.js:282:5
>     at Array.forEach (<anonymous>)
>     at forEachKeyedObject (/home/admin/workplace/node_modules/loopback-boot/lib/executor.js:281:20)
>     at setupDataSources (/home/admin/workplace/node_modules/loopback-boot/lib/executor.js:181:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! Workplace@1.0.0 start-production: `NODE_ENV=development node .`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the Workplace@1.0.0 start-production script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/admin/.npm/_logs/2019-03-25T07_10_46_940Z-debug.log
> 

And in the ` /home/admin/.npm/_logs/2019-03-25T07_10_46_940Z-debug.log` it give me this:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'start-production' ]
> 2 info using npm@6.9.0
> 3 info using node@v8.11.3
> 4 verbose run-script [ 'prestart-production',
> 4 verbose run-script   'start-production',
> 4 verbose run-script   'poststart-production' ]
> 5 info lifecycle Workplace@1.0.0~prestart-production: Workplace@1.0.0
> 6 info lifecycle Workplace@1.0.0~start-production: Workplace@1.0.0
> 7 verbose lifecycle Workplace@1.0.0~start-production: unsafe-perm in lifecycle true
> 8 verbose lifecycle Workplace@1.0.0~start-production: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/admin/workplace/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
> 9 verbose lifecycle Workplace@1.0.0~start-production: CWD: /home/admin/workplace
> 10 silly lifecycle Workplace@1.0.0~start-production: Args: [ '-c', 'NODE_ENV=development node .' ]
> 11 silly lifecycle Workplace@1.0.0~start-production: Returned: code: 1  signal: null
> 12 info lifecycle Workplace@1.0.0~start-production: Failed to exec start-production script
> 13 verbose stack Error: Workplace@1.0.0 start-production: `NODE_ENV=development node .`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid Workplace@1.0.0
> 15 verbose cwd /home/admin/workplace
> 16 verbose Linux 4.15.0-46-generic
> 17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-production"
> 18 verbose node v8.11.3
> 19 verbose npm  v6.9.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error Workplace@1.0.0 start-production: `NODE_ENV=development node .`
> 22 error Exit status 1
> 23 error Failed at the Workplace@1.0.0 start-production script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by harishanchu** [comment]
This looks like a database connectivity issue. I guess you followed the second installation method(Run directly on your workstation) from the documentation, If so did you make changes to application configuration files as mentioned in this step: 

> Modify [configuration](https://github.com/harishanchu/workplace#configuration) files in the repository directory as needed(modify db host address, smtp configuration etc).

**Comment by akhlaaqbadulla** [comment]
yes i did modify. but on running i get ths error as well.

> root@serverga:/opt/workplace# npm run start-production
> 
> > Workplace@1.0.0 start-production /opt/workplace
> > NODE_ENV=development node .
> 
> Connection fails: Error: getaddrinfo ENOTFOUND mysql mysql:3306
> It will be retried for the next request.
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: getaddrinfo ENOTFOUND mysql mysql:3306
>     at errnoException (dns.js:50:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
>     --------------------
>     at Protocol._enqueue (/opt/workplace/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>     at Protocol.handshake (/opt/workplace/node_modules/mysql/lib/protocol/Protocol.js:51:23)
>     at PoolConnection.connect (/opt/workplace/node_modules/mysql/lib/Connection.js:118:18)
>     at Pool.getConnection (/opt/workplace/node_modules/mysql/lib/Pool.js:48:16)
>     at MySQL.connect (/opt/workplace/node_modules/loopback-connector-mysql/lib/mysql.js:90:17)
>     at Object.initializeDataSource [as initialize] (/opt/workplace/node_modules/loopback-connector-mysql/lib/mysql.js:44:28)
>     at DataSource.setup (/opt/workplace/node_modules/loopback-datasource-juggler/lib/datasource.js:493:19)
>     at new DataSource (/opt/workplace/node_modules/loopback-datasource-juggler/lib/datasource.js:138:8)
>     at Registry.createDataSource (/opt/workplace/node_modules/loopback/lib/registry.js:364:12)
>     at dataSourcesFromConfig (/opt/workplace/node_modules/loopback/lib/application.js:570:19)
>     at Function.app.dataSource (/opt/workplace/node_modules/loopback/lib/application.js:269:14)
>     at /opt/workplace/node_modules/loopback-boot/lib/executor.js:191:9
>     at /opt/workplace/node_modules/loopback-boot/lib/executor.js:282:5
>     at Array.forEach (<anonymous>)
>     at forEachKeyedObject (/opt/workplace/node_modules/loopback-boot/lib/executor.js:281:20)
>     at setupDataSources (/opt/workplace/node_modules/loopback-boot/lib/executor.js:181:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! Workplace@1.0.0 start-production: `NODE_ENV=development node .`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the Workplace@1.0.0 start-production script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-03-29T07_21_13_239Z-debug.log

**Comment by awurecursionco** [comment]
Hello, i can start the applications, tables were created and webpage is up.  it can also register users but when I tried to login, the errors says email can't be verified. I tried to use admin to login it says login failed.
any idea how to troubleshoot the issue?

**Comment by harishanchu** [comment]
Users must recieve a verification link email after account registration. Users should click on that verification link to confirm the email to be able to login. I hope you have configured smtp details in the application in here: https://github.com/harishanchu/workplace/blob/master/server/datasources.json

**Comment by awurecursionco** [comment]
yes i did configure the db and I can see user email  was in the table.  but user isn’t getting email  after  register.  i figure user should get an email for verification
